In [1]:
# Cheak gpu
!nvidia-smi

Fri Dec  1 21:08:55 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 529.04       Driver Version: 529.04       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   44C    P5     7W /  94W |    588MiB /  8188MiB |      8%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow_hub as hub
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [3]:
train = pd.read_csv("train/train/train.csv")
test = pd.read_csv("test/test/test.csv")

In [4]:
print (train)

      image_id  filename  label
0            1     1.jpg      2
1            2     2.jpg      4
2            3     3.jpg      2
3            4     4.jpg      3
4            5     5.jpg      5
...        ...       ...    ...
7195      7196  7196.jpg      4
7196      7197  7197.jpg      4
7197      7198  7198.jpg      4
7198      7199  7199.jpg      2
7199      7200  7200.jpg      2

[7200 rows x 3 columns]


In [5]:
print(test)

      image_id   filename
0         7201   7201.jpg
1         7202   7202.jpg
2         7203   7203.jpg
3         7204   7204.jpg
4         7205   7205.jpg
...        ...        ...
4795     11996  11996.jpg
4796     11997  11997.jpg
4797     11998  11998.jpg
4798     11999  11999.jpg
4799     12000  12000.jpg

[4800 rows x 2 columns]


In [6]:
train_folder = "train/train/images"
test_folder = "test/test/images"

In [7]:
# Define your data generator
train_gen = ImageDataGenerator(
rotation_range=45,
rescale=1./255,
horizontal_flip=True
)
test_gen = ImageDataGenerator(rescale = 1./255)

In [8]:
filename = 'filename' 
label = 'label'

In [16]:
# # Assuming you have your original training data in 'train_data'
# train_data, val_data = train_test_split(train, test_size=0.2, random_state=42)

In [9]:
train_data = train_gen.flow_from_dataframe( dataframe = train, 
                                            directory = train_folder, x_col = filename, 
                                            y_col = label, seed = 42,
                                            batch_size = 32, shuffle = True, 
                                            class_mode="raw",target_size = (224, 224))

# val_data = train_gen.flow_from_dataframe(
#                                                 dataframe=val_data,
#                                                 directory=train_folder,  # Assuming validation data is in the same folder as training data
#                                                 x_col=filename,
#                                                 y_col=label,
#                                                 seed=42,
#                                                 batch_size=32,
#                                                 shuffle=False,
#                                                 class_mode="sparse",
#                                                 target_size=(224, 224)
# )

test_data = test_gen.flow_from_dataframe(   dataframe = test, 
                                            directory = test_folder, x_col = filename, 
                                            y_col = None,
                                            batch_size = 32, shuffle = False, 
                                            class_mode=None,target_size = (224, 224))

Found 7200 validated image filenames.
Found 4800 validated image filenames.


In [18]:
train_data

In [46]:
import numpy as np

# Assuming train_data is your DataFrameIterator
batch = next(train_data)

# Extract data and labels from the batch
images, labels = batch

labels = labels.astype(np.float32)


In [47]:
batch

(array([[[[0.9239305 , 0.26902854, 0.4886364 ],
          [0.9272554 , 0.27235332, 0.49196118],
          [0.93058014, 0.27567816, 0.49528602],
          ...,
          [0.9948733 , 0.85296446, 0.8021672 ],
          [0.8940659 , 0.7380827 , 0.6897926 ],
          [0.97647065, 0.8356729 , 0.761838  ]],
 
         [[0.9740081 , 0.319106  , 0.53871393],
          [0.9706832 , 0.31578124, 0.53538907],
          [0.9673584 , 0.3124564 , 0.53206426],
          ...,
          [0.9882237 , 0.84536487, 0.79480505],
          [0.8992907 , 0.74449486, 0.6945423 ],
          [0.97647065, 0.8306858 , 0.7578007 ]],
 
         [[0.9203936 , 0.2654916 , 0.48509946],
          [0.92395586, 0.2690539 , 0.48866177],
          [0.9275182 , 0.27261618, 0.49222404],
          ...,
          [0.981574  , 0.83776534, 0.787443  ],
          [0.9045153 , 0.75090694, 0.699292  ],
          [0.97647065, 0.82569855, 0.7537634 ]],
 
         ...,
 
         [[0.6569521 , 0.6569521 , 0.6569521 ],
          [0.62349

In [40]:
images

<tf.Tensor: shape=(32, 224, 224, 3), dtype=float32, numpy=
array([[[[0.1296265 , 0.14531277, 0.15465821],
         [0.07340999, 0.08909626, 0.0945647 ],
         [0.03816466, 0.05385094, 0.05777251],
         ...,
         [0.34910387, 0.39502418, 0.42808345],
         [0.28760058, 0.33858097, 0.3699535 ],
         [0.2634084 , 0.31438878, 0.34576133]],

        [[0.0789327 , 0.09461897, 0.10638368],
         [0.15453422, 0.1702205 , 0.1819852 ],
         [0.11605293, 0.1317392 , 0.14014854],
         ...,
         [0.3199504 , 0.3709308 , 0.40230337],
         [0.24495356, 0.29593396, 0.3273065 ],
         [0.3021784 , 0.3531588 , 0.38453135]],

        [[0.02863161, 0.04431789, 0.0560826 ],
         [0.0215853 , 0.03727157, 0.04903628],
         [0.09718683, 0.1128731 , 0.1246378 ],
         ...,
         [0.27730337, 0.32828376, 0.35965633],
         [0.27276948, 0.32374987, 0.35512242],
         [0.28269508, 0.33367547, 0.36504802]],

        ...,

        [[0.4409756 , 0.44256708,

In [34]:
labels

array([2., 4., 4., 5., 4., 4., 6., 5., 2., 2., 5., 2., 2., 2., 4., 6., 4.,
       5., 6., 2., 5., 4., 2., 6., 2., 2., 5., 4., 3., 2., 2., 2.],
      dtype=float32)

In [35]:
# # Assuming you have your original training data in 'train_data'
# train_data, val_data = train_test_split(train, test_size=0.2, random_state=42)
# Build a CNN model(same as tiny VGG )

model_1 = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(filters=10,
                           kernel_size = 3,
                           activation="relu",
                           input_shape=(224, 224, 3)),
    tf.keras.layers.Conv2D(10, 3, activation="relu"),
    tf.keras.layers.MaxPool2D(pool_size=2,
                              padding="valid"),
    tf.keras.layers.Conv2D(10, 3, activation="relu"),
    tf.keras.layers.Conv2D(10, 3, activation="relu"),
    tf.keras.layers.MaxPool2D(2),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(6, activation="sigmoid")
])

model_1.compile(loss= "sparse_categorical_crossentropy",
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])


In [13]:
type(train_data)

keras.src.preprocessing.image.DataFrameIterator

In [50]:
import tensorflow as tf
from tensorflow.keras import layers, models

# Define the EfficientNetV2 base model
base_model = tf.keras.applications.efficientnet_v2.EfficientNetV2B0(include_top=False)
base_model.trainable = False

# Create input layers for images and labels
image_input = tf.keras.layers.Input(shape=(224, 224, 3), name="image_input")
label_input = tf.keras.layers.Input(shape=(1,), name="label_input")

# Pass images through the base model
x = base_model(image_input)
x = tf.keras.layers.GlobalAveragePooling2D(name="global_average_pooling_layer")(x)

# Concatenate the flattened image tensor with the label input
concatenated = tf.keras.layers.concatenate([x, label_input])

# Create the output layer
outputs = tf.keras.layers.Dense(6, activation="softmax", name="output_layer")(concatenated)

# Combine the inputs with the outputs into a model
model_0 = tf.keras.Model(inputs=[image_input, label_input], outputs=outputs)

# Compile the model
model_0.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])


In [48]:
# 1. Create a base model tf.keras.application

base_model = tf.keras.applications.efficientnet_v2.EfficientNetV2B0(include_top=False)

# 2. freeze the base model
base_model.trainable = False

# 3. Create inputs into our model
inputs = tf.keras.layers.Input(shape=(224,224,3), name="input_layer")

# 4. for resnet

# 5. Pass the inputs to the base model
x = base_model(inputs)
print(f"Shape after passing inputs through base model: {x.shape}")

# 6. Avarage pool outputs of the model (aggregation all the most important information, reduce number of computations)
x = tf.keras.layers.GlobalAveragePooling2D(name = "Gloabal_average_pooling_layer")(x)
print(f"Shape after GlobalAveragePooling2D: {x.shape}")

# 7. Create the output activation layer
outputs = tf.keras.layers.Dense(6, activation="softmax", name="output_layer")(x)

# 8. combine the inputes with the outputs into a model
model_0 = tf.keras.Model(inputs, outputs)

#9. Compile the model
model_0.compile(loss= "sparse_categorical_crossentropy",
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

# # 10. fit the model

# history_model_0 = model_0.fit(train_data,
#                                  epochs = 5,
#                                  steps_per_epoch=len(train_data),
#                                  validation_data=val_data,
#                                  validation_steps=val_data
#                                  )



Shape after passing inputs through base model: (None, 7, 7, 1280)
Shape after GlobalAveragePooling2D: (None, 1280)


In [43]:
model_1.compile(loss= "sparse_categorical_crossentropy",
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])


In [51]:
# 10. fit the model

history_model_0 = model_0.fit(batch,
                                 epochs = 5,
                                 steps_per_epoch=len(batch),
                                 validation_split=0.2,
                                 validation_steps=int(0.25 * len(batch))
                                 )



Epoch 1/5


ValueError: in user code:

    File "c:\Users\ADMIN\anaconda3\envs\tf\Lib\site-packages\keras\src\engine\training.py", line 1377, in train_function  *
        return step_function(self, iterator)
    File "c:\Users\ADMIN\anaconda3\envs\tf\Lib\site-packages\keras\src\engine\training.py", line 1360, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\Users\ADMIN\anaconda3\envs\tf\Lib\site-packages\keras\src\engine\training.py", line 1349, in run_step  **
        outputs = model.train_step(data)
    File "c:\Users\ADMIN\anaconda3\envs\tf\Lib\site-packages\keras\src\engine\training.py", line 1128, in train_step
        self._validate_target_and_loss(y, loss)
    File "c:\Users\ADMIN\anaconda3\envs\tf\Lib\site-packages\keras\src\engine\training.py", line 1082, in _validate_target_and_loss
        raise ValueError(

    ValueError: Target data is missing. Your model was compiled with loss=sparse_categorical_crossentropy, and therefore expects target data to be provided in `fit()`.


In [5]:
import pandas as pd
df = pd. read_csv("train/train/train.csv")
print (df)

      image_id  filename  label
0            1     1.jpg      2
1            2     2.jpg      4
2            3     3.jpg      2
3            4     4.jpg      3
4            5     5.jpg      5
...        ...       ...    ...
7195      7196  7196.jpg      4
7196      7197  7197.jpg      4
7197      7198  7198.jpg      4
7198      7199  7199.jpg      2
7199      7200  7200.jpg      2

[7200 rows x 3 columns]


In [22]:
image_folder = 'train/train/images'
image_names = df['filename']
labels = df['label']

In [23]:
# Split data
train_images, val_images, train_labels, val_labels = train_test_split(
    image_names, labels, test_size=0.2, random_state=42)

In [24]:
print(train_labels)

2034    5
3250    5
3366    4
1423    2
122     4
       ..
3772    4
5191    4
5226    4
5390    2
860     4
Name: label, Length: 5760, dtype: int64


In [25]:
IMAGE_SHAPE = (224,224)
BATCH_SIZE = 32

In [19]:
# Data augmentation
train_gen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    
)
# Define your data generator
 
test_gen = ImageDataGenerator(rescale = 1./255)

In [ ]:
train_data = train_gen.flow_from_dataframe(directory=train_dir,
                                                                            image_size=IMG_SIZE,
                                                                            label_mode="categorical",
                                                                            batch_size=BATCH_SIZE)

test_data = tf.keras.preprocessing.image_dataset_from_directory(directory= test_dir,
                                                                image_size= IMG_SIZE,
                                                                label_mode="categorical",
                                                                batch_size=BATCH_SIZE)

In [ ]:
train_data = train_gen.flow_from_dataframe(dataframe = train, 
                                           directory = train_folder, x_col = name of your column with image, 
y_col = name of column of your labels, seed = 42,
batch_size = size of your batch, shuffle = True, 
class_mode="categorical",target_size = (height of image, width of image))

test_data = test_gen.flow_from_dataframe(dataframe = test, 
directory = test_folder, x_col = name of your column with image, 
y_col = None,
batch_size = size of your batch, shuffle = False, 
class_mode=None,target_size = (height of image, width of image))

In [15]:
# def preprocess_image(img_path, label):
#     img = load_and_preprocess_image(img_path)  # Custom function to load and preprocess image
#     label = one_hot_encode(label)  # Custom function for one-hot encoding
#     return img, label


In [16]:
# # Apply preprocessing to training and validation data
# train_data = [(preprocess_image(image_folder + img, label)) for img, label in zip(train_images, train_labels)]
# val_data = [(preprocess_image(image_folder + img, label)) for img, label in zip(val_images, val_labels)]

NameError: name 'load_and_preprocess_image' is not defined